Add Room entity, Room manager (initial structure) and some Exceptions
gnievestm/library-management pull request #1
Opened 2023-10-18 12:58 UTC by Benjamin-Chain

## Summary
- Created room entity
- Created room manager
- Created custom exceptions
- Unit testing over functionality

2023-10-18 14:40 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
> +    static int roomIds=0;
Please make the roomsIds variable private, there is no need to have this one as default.

2023-10-18 14:40 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
> +    public static int getRoomIds() {
Same here, there is no need to expose that variable outside.

2023-10-18 14:41 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
> +    public boolean equals(Object o) {
Given that there is an Id for the rooms. wouldn't it be possible to use the id for the equals?

2023-10-18 14:43 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/exceptions/room/RoomIncompleteFieldsException.java
> +        super("Some required fields are incomplete");
this error message can be a little bit more specific

2023-10-18 15:03 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/exceptions/room/RoomIncompleteFieldsException.java
> +public class RoomIncompleteFieldsException extends Exception{
Please apply the formatter to the code, the braces should have a space before opening.

2023-10-18 15:03 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/exceptions/room/RoomNotFoundException.java
> +public class RoomNotFoundException extends Exception{
same here it should be Exception {

2023-10-18 15:03 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/exceptions/room/RoomNotFoundException.java
> +        super("Room not found");
and here as well

2023-10-18 15:04 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/managers/RoomManager.java
> +    private List<Room> rooms;
does rooms hold all the rooms or just the ones available? please name accordingly the variable.

2023-10-18 15:07 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/managers/RoomManager.java
> +        if(room.getName() == null || room.getAddress() == null || room.getName().isEmpty() || room.getAddress().isEmpty()){
I think this error should arise directly from the creation of the room, (when doing the new) as it is the room responsibility to decide which fields are compulsory an which ones aren't.

2023-10-18 15:08 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/managers/RoomManager.java
> +        reservedRooms.add(room);
adding a room here to the reserve rooms does not guarantee the room exists.

2023-10-18 15:10 UTC, gnievestm commented on src/test/java/com/teamcubation/librarymanagement/domain/RoomServiceTest.java
It looks like the main functionality created in this pr is over roomManager, I would expect to have test over it as well.

2023-10-18 15:10 UTC, gnievestm requested changes
Please check out the comments. Otherwise, great work.

2023-10-18 15:11 UTC, gnievestm commented
Please add a brief decription of the work done in the pr description.

2023-10-18 15:12 UTC, gnievestm commented
Curthermore name the branches as {action}/{jira-ticket}-{brief-description-kebab-case}

2023-10-18 15:12 UTC, Benjamin-Chain commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
> +    static int roomIds=0;
resolved

2023-10-18 15:12 UTC, Benjamin-Chain commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
> +    public static int getRoomIds() {
Thanks for the feedback

2023-10-18 15:13 UTC, Benjamin-Chain commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
> +    public boolean equals(Object o) {
You have all reason, I think it's already resolved

2023-10-18 15:13 UTC, Benjamin-Chain commented on src/main/java/com/teamcubation/librarymanagement/domain/exceptions/room/RoomIncompleteFieldsException.java
> +        super("Some required fields are incomplete");
I think it's already resolved and with a high level of specification

2023-10-18 15:14 UTC, Benjamin-Chain commented on src/main/java/com/teamcubation/librarymanagement/domain/exceptions/room/RoomIncompleteFieldsException.java
> +public class RoomIncompleteFieldsException extends Exception{
Okay, thanks

2023-10-19 12:37 UTC, Benjamin-Chain commented
I think I have done all the corrections possible

2023-10-19 13:01 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
>      }
There should be a blank line after finishing a methods for reading simplicity

2023-10-19 13:02 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
> +    public Room(int id, String name, String address) throws RoomIncompleteFieldsException, RoomInvalidIdException {
**I haven't check yet if it is done** -> given that the id is externally provided, the system should check if the id is unique in the manager before adding.

2023-10-19 13:04 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Room.java
> +    public Room(int id, String name, String address) throws RoomIncompleteFieldsException, RoomInvalidIdException {
Found the check in the code :) well done.

2023-10-19 13:05 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/managers/RoomManager.java
> +            throw new RoomAlreadyExistsException();
It seems like the exception here is that the room is already reserved, not that it already exists right?

2023-10-19 13:07 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/managers/RoomManager.java
>              throw new RoomIncompleteFieldsException();
There is no need to check if the room has the necessary fields, we can safely assume that only rooms that have already been added are avaialble for reserve, basically there are 2 possible cases, the room exist and it is reserved or it doesn't and an error is thrown. Regarding errors there should be 2 errors, room not found or room not available.

2023-10-19 15:48 UTC, leosilva12 approved these changes

2023-10-19 15:48 UTC, merged