Implement the entity Book, the ManagerBook, BookService the method ad…
gnievestm/library-management pull request #4
Opened 2023-10-18 14:37 UTC by ZayannaPinochet

…d and the unit tests

2023-10-18 15:13 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    static int id=0;
please set this static value as private, there is no utility in exposing it.

2023-10-18 15:13 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    public Book(String title,String autor,String publishYear){
Please apply the formatter before pushing any file. There should be a space after every comma as well as space before braces

2023-10-18 15:14 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    static int id=0;
Furthemore, try to use a name that makes clearer that the id is an instance value.

2023-10-18 15:15 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    public static int getId() {
Please make the getId private as there is no need to share this information outside the class.

2023-10-18 15:15 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    public static int getId() {
or it can be removed as it is not needed.

2023-10-18 15:15 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    private String autor;
typo: autHor

2023-10-18 15:17 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    private String publishYear;
YearOfPublishing sound better, wouldn't it be more useful to use a date type here?

2023-10-18 15:21 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +        return Objects.equals(autor, book.autor) && Objects.equals(title, book.title) && Objects.equals(publishYear, book.publishYear);
if there is an id to identify a book it would be worth it to use it, given that there might be 2 copies of the same book and the equals is going to say it is exactly the same.

2023-10-18 15:22 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/exceptions/book/BookSomeEmptyAttributeException.java
> +        super("It´s impossible to add an element that has some empty attribute");
That message error can be simplified to "Element with missing attributes cannot be added."

2023-10-18 15:32 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/managers/BookManager.java
> +            throw new BookSomeEmptyAttributeException();
it is not responibility of the manager to create a book, nor should be checking if the book is well built

2023-10-18 15:32 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/managers/BookManager.java
> +    public boolean existBook(Book book){
Once the equals is this code might need to change.

2023-10-18 15:33 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/service/BookService.java
> +            instance=new BookService();
Apply formatter please.

2023-10-18 15:33 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/service/BookService.java
> +        Book book=new Book(title,autor,publishYear);
Here is the code creating a book, thus the service is being held responsible of that action.

2023-10-18 15:36 UTC, gnievestm commented on src/test/java/com/teamcubation/librarymanagement/domain/BookServiceTest.java
> +        BookSomeEmptyAttributeException exception =assertThrows(BookSomeEmptyAttributeException.class,()->{
why is there an arrow function here?

2023-10-18 15:37 UTC, gnievestm commented on src/test/java/com/teamcubation/librarymanagement/domain/BookServiceTest.java
> +        assertEquals(exception.getMessage(),"It´s impossible to add an element that has some empty attribute");
given that the assertThrows is already checking the exception class is correct, there is no need to do the assert equals as well.

2023-10-18 15:39 UTC, gnievestm requested changes
Please review the comments. Great work in general terms.

2023-10-19 11:58 UTC, ZayannaPinochet commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    private String publishYear;
I´m going to use the Class Year of Java Time

2023-10-19 12:45 UTC, ZayannaPinochet commented on src/test/java/com/teamcubation/librarymanagement/domain/BookServiceTest.java
> +        BookSomeEmptyAttributeException exception =assertThrows(BookSomeEmptyAttributeException.class,()->{
I use the arrow function because I investigate and saw that in JUnit 5 I should use this way of implement exceptions in my tests

2023-10-19 12:49 UTC, ZayannaPinochet commented on src/main/java/com/teamcubation/librarymanagement/service/BookService.java
> +        Book book=new Book(title,autor,publishYear);
I apply some changes like add the condition that neither attribute could be empty inside it, because I understood that in the instance and add in BookManager must be checked

2023-10-19 13:12 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/service/BookService.java
> +        Book book=new Book(title,autor,publishYear);
What I meant, is that here is where the book is created, and the conditions should be checked here

2023-10-19 13:12 UTC, gnievestm commented on src/test/java/com/teamcubation/librarymanagement/domain/BookServiceTest.java
> +        BookSomeEmptyAttributeException exception =assertThrows(BookSomeEmptyAttributeException.class,()->{
well done

2023-10-20 12:38 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/entities/Book.java
> +    static int predefinedBookId = 0;
Not right now  but we should change this name as it is not descriptive enough of the functionality

2023-10-20 12:42 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/domain/managers/BookManager.java
> +    }
There should be a blank line here

2023-10-20 12:43 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/service/BookService.java
> +    public int countBook(){
countbook -> bookCount

2023-10-20 12:43 UTC, gnievestm commented on src/main/java/com/teamcubation/librarymanagement/service/UserService.java
> +
This blank line should not be here

2023-10-20 12:44 UTC, gnievestm approved these changes
There are some small details we should fix in the future sprint. Great job

2023-10-20 12:44 UTC, merged